name: Desolate-KD
version: '${project.version}'
main: org.desolate.DESOLATE_KD
api-version: '1.16'
author: MoresForDESOLATE
commands:
  kd:
    description: Calculate and display player`s KD
    usage: /kd